### ISSUE TITLE
System.TypeLoadException: Could not load type 'System.Windows.Forms.AnchorStyles' from assembly 'FastReport.Compat, Version=2022.2.0.0, Culture=neutral, PublicKeyToken=406e1f4c3c8ef97e'.

### ISSUE THREAD

**Issue by DemonJtan** [FastReports/FastReport#451] opened 2022-06-30 02:04 UTC
The latest version Release2022.2.12,when I use the following code  "Report report = new Report();"  in my .NET 5.0 Project，there throws a exception
![image](https://user-images.githubusercontent.com/20058248/176576662-d57dc2c7-8b33-4ae7-9246-2ecff42166a4.png)

**Comment by StephaneDelhautal** [comment] 2022-07-04 13:43
Hi,

same error for me.
i have create a a report with fastreport designer and save it as vb class file.
in visual studio, i have a sample projet, put the report vb class in the projet directory , this file contains the class definition FicheSuiviAssemblage
in my main form, i have added a button with this code:
Dim MyReport As New FicheSuiviAssemblage
complition is fine. and when i run the projet and click on my button, the error is triggered on this instruction

![image](https://user-images.githubusercontent.com/101656556/177167148-5cf725ae-b944-410e-8875-13513252a951.png)

**Comment by valentinistrate** [comment] 2022-07-07 14:19
The error can be reproduces by using the attached project:

[ExampleWPFWithFastReports.zip](https://github.com/FastReports/FastReport/files/9064560/ExampleWPFWithFastReports.zip)
.

**Comment by jeremyc87** [comment] 2022-07-15 06:56
I have the exact same problem here.
I am using .NET 6.0 in WPF.

The error also occur if I use report.FromFile().

**Comment by jeremyc87** [comment] 2022-07-18 14:47
Hello again,

Because of this issue I am not able to test this product properly and I must make a decision quickly.

Is somebody working on it? Did you have any idea how to fix it and when can we expect a working version?

I know it's a free version and as such the support is not as quick and as "performing" but I really like the idea of this product and I would be sad to discard it because a little bug like that make me unable to properly test it.

Thanks anyway and good luck with this.
Best regards!

**Comment by jonmpoole80** [comment] 2022-07-18 17:41
Just ran into this myself and this topic was the first result when googling it. I am also having the issue in Report.ReadFromFile().

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'FastReport.Report' threw an exception.
  Source=FastReport
  StackTrace:
   at FastReport.Report.FromFile(String fileName)
   at FulcrumDatabaseUpdater.frmStockReports.btnUpdate_Click(Object sender, EventArgs e) in C:\Users\jpoole.CREATIVEINFO\source\repos\Valsoft-Industrial-Division\FulcrumDatabaseUpdater\FulcrumDatabaseUpdater\frmStockReports.cs:line 98
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TypeLoadException: Could not load type 'System.Windows.Forms.AnchorStyles' from assembly 'FastReport.Compat, Version=2022.2.0.0, Culture=neutral, PublicKeyToken=406e1f4c3c8ef97e'.
```

![image](https://user-images.githubusercontent.com/96305787/179570733-a8731405-987b-4b4c-86be-90523746a1ac.png)

**Comment by blackflys** [comment] 2022-07-19 16:38
I also have this problem, is it possible that the FastReport.Compat is referenced by multiple projects inside and not all have the same version?

`Could not load type 'System.Windows.Forms.AnchorStyles' from assembly 'FastReport.Compat, Version=2022.2.0.0, Culture=neutral, PublicKeyToken=406e1f4c3c8ef97e'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Plateforme.Core.StartupBase.<>c.<.ctor>b__4_1(Assembly x)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Plateforme.Core.StartupBase.<>c.<.ctor>b__4_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Something.Core.StartupBase.get_ModuleInitializers()
   at Something.Core.StartupBase.ConfigureServices(IServiceCollection services)
   at Something.Core.StartupConsoleBase.ConfigureServices(IServiceCollection services)
   at Something.Core.Extensions.HostBuilderExtensions.UseStartup[TStartup](IHostBuilder hostBuilder)
`

**Comment by allen3371** [comment] 2022-07-20 09:07
same to me

**Comment by sayoojsushand** [comment] 2022-07-30 18:39
Same issue for me using .NET 6.
Temporary fix was to use FastReport.OpenSource NuGet package version 2022.1.14

**Comment by KirillKornienko** [comment] 2022-08-08 07:02
This bug was fixed in 2022.2.17. Please, update and try it.

**Closed** 2022-08-23 08:15 UTC

**Comment by moelang** [comment] 2022-09-01 06:51
I reproduced this problem in 2022.2.14/17/18, and not reproduced in 2022.1.14

> This bug was fixed in 2022.2.17. Please, update and try it.

**Comment by Kalina9001** [comment] 2022-09-06 08:00
Same Error! 
Any changes?

**Comment by AlekseyKrutko** [comment] 2023-04-26 13:51
Any workarounds? It is still reproducible

**Comment by AlekseyKrutko** [comment] 2023-04-27 12:49
If anyone iterested. For me the reason was that Report usage is in a dynamicaly loaded assembly and in the way how dependencies are resolved. Using AssemblyLoadContext + AssemblyDependencyResolver fixed the problem.
AssemblyDependencyResolver is not accessible for net framework.
Here is a project that implements two ways. The first one reproduces the problem.
[WpfWithFastReportFailing.zip](https://github.com/FastReports/FastReport/files/11343627/WpfWithFastReportFailing.zip)

**Comment by duduccosta** [comment] 2024-03-22 15:48
I'm facing this error:

Could not load type 'System.Windows.Forms.AnchorStyles' from assembly 'FastReport.Compat, Version=2024.1.10.0, Culture=neutral, PublicKeyToken=5ceb240df42bf6e8'.

Using .NET7

**Comment by LordRUSS** [comment] 2024-03-25 16:51
I'm facing this error:

TypeLoadException: Could not load type 'System.Windows.Forms.AnchorStyles' from assembly 'FastReport.Compat, Version=2024.1.10.0, Culture=neutral, PublicKeyToken=5ceb240df42bf6e8'.

Using .NET8

**Comment by Elbunda7** [comment] 2024-03-27 08:51
This issue should not be closed, because the exception System.TypeLoadException is still throwing in version 2024.1.10 when "Report report = new Report();" is called.

Current workaround is to use a few year old version 2022.1.14 of FastReport.Opensource and 2021.3.1 version of FastReport.Compat

**Comment by duduccosta** [comment] 2024-03-27 12:26
This error happens on PRO version too..

**Comment by BogdanStegachev** [comment] 2024-03-27 12:47
Hello!

Reproduced this issue, created a task and passed it to the development department, expect changes soon

Best regards,
Bogdan

**Comment by wagenheimer** [comment] 2024-03-29 00:50
Is there a workaround for the most recents PRO Version?

**Comment by AlekseyKrutko** [comment] 2024-03-29 12:13
> Is there a workaround for the most recents PRO Version?

Try to ensure that \bin\Debug\net6.0-windows\runtimes\any\lib\netcoreapp3.0\FastReport.Compat.dll is loaded.
I just copy it into project output root

  
  <Target Name="CopyFastReportCompatDLL" AfterTargets="Build" Condition="'$(TargetFramework)' == 'net6.0-windows'">
    <Message Text="Copying FastReport.Compat.dll" Importance="High" />
    <Copy SourceFiles="$(OutputPath)runtimes\any\lib\netcoreapp3.0\FastReport.Compat.dll" DestinationFolder="$(OutputPath)" />
    <Message Text="Copied FastReport.Compat.dll" Importance="High" />
  </Target>
